let card = document.getElementById("card");

let products = [
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: true,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://st.inmebelstil.ru/8/2318/354/mebel_voronezh_katalog_kuhni1.jpg",
    discount: "",
    saved: false,
    id: "6",
    categoryId: "1",
  },
  {
    name: "Барные стулья",
    title: "Толикс-2 White Gloss",
    price: "230",
    active: false,
    description: "",
    width: "45",
    height: "88",
    depth: "79",
    img: "https://realmebel.pro/upload/iblock/c60/c601fd8a907c1c58eeff1b564c6f530d.jpg",
    discount: "",
    saved: false,
    id: "4",
    categoryId: "1",
  },
];

products.forEach((item) => {
  card.innerHTML += `
        <div class="product">
            <button class="heart" onclick="changeColor()"><ion-icon name="heart"></ion-icon></button>
            <img class="aa" src="${item.img}" alt="product">
            <div class="title">
                <h3>${item.name}</h3>
                <p>${item.title}</p>
                <h4>${item.price}</h4>
                <p>Размеры</p>
                <div class="size">
                  <div class="block">
                    <h4>ШИРИНА</h4>
                    <p>${item.width} СМ</p>
                  </div>
                  <div class="block">
                    <h4>ВЫСОТА</h4>
                    <p>${item.height} СМ</p>
                  </div>
                  <div class="block">
                    <h4>ГЛУБИНА</h4>
                    <p>${item.depth} СМ</p>
                  </div>
                </div>
                <button>shop now</button>
            </div>
        </div>`;
});
